import { ReadinessReport } from '../types';

export function createDemoReport(): ReadinessReport {
  return {
    repoUrl: 'https://github.com/demo/shipcheck-demo',
    analyzedAt: new Date().toISOString(),
    metadata: {
      owner: 'demo',
      name: 'shipcheck-demo',
      fullName: 'demo/shipcheck-demo',
      description: 'A demo repository for ShipCheck AI testing',
      defaultBranch: 'main',
      isPrivate: false,
      stars: 42,
      forks: 12,
      openIssues: 3,
      language: 'TypeScript',
      topics: ['demo', 'testing', 'shipcheck'],
      hasWiki: true,
      license: 'MIT',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      size: 1024,
    },
    score: {
      total: 72,
      grade: 'C',
      breakdown: {
        readme: 18,
        build_config: 15,
        security: 16,
        links: 6,
        repo_hygiene: 10,
        license: 7,
      },
    },
    findings: [
      {
        id: 'readme_missing_setup',
        category: 'readme',
        severity: 'critical',
        title: 'Missing Setup Instructions',
        description: 'README does not contain clear installation or setup instructions.',
        evidence: 'README.md section: No installation steps found',
        suggestion: 'Add prerequisites, installation commands, environment setup, and run instructions.',
      },
      {
        id: 'readme_missing_env',
        category: 'readme',
        severity: 'warning',
        title: 'Environment Variables Not Documented',
        description: 'README does not document required environment variables.',
        evidence: 'README.md section: No environment variable documentation found',
        suggestion: 'Add a section documenting all required environment variables with examples.',
      },
      {
        id: 'security_committed_env',
        category: 'security',
        severity: 'critical',
        title: 'Potential Secret Exposure',
        description: 'Committed .env file detected. This may contain sensitive credentials.',
        evidence: '.env file found in repository root',
        suggestion: 'Remove .env from git history and add to .gitignore. Use .env.example instead.',
      },
      {
        id: 'links_broken_demo',
        category: 'links',
        severity: 'warning',
        title: 'Broken Demo Link',
        description: 'Demo link in README appears to be broken or unreachable.',
        evidence: 'Link: https://demo.example.com - Status: Could not verify',
        suggestion: 'Update the demo link or remove it if the demo is not available.',
      },
      {
        id: 'build_missing_test',
        category: 'build_config',
        severity: 'warning',
        title: 'No Test Configuration',
        description: 'No test configuration detected in the repository.',
        evidence: 'package.json: No test script found',
        suggestion: 'Add test scripts to package.json and document how to run tests.',
      },
      {
        id: 'repo_hygiene_contributing',
        category: 'repo_hygiene',
        severity: 'info',
        title: 'No CONTRIBUTING.md',
        description: 'Repository lacks a CONTRIBUTING.md file.',
        evidence: 'File not found in repository root',
        suggestion: 'Add a CONTRIBUTING.md to guide contributors on how to participate.',
      },
      {
        id: 'readme_missing_architecture',
        category: 'readme',
        severity: 'info',
        title: 'No Architecture Documentation',
        description: 'README does not include architecture or workflow explanation.',
        evidence: 'README.md section: No architecture section found',
        suggestion: 'Add a section explaining the project architecture and data flow.',
      },
      {
        id: 'security_env_example',
        category: 'security',
        severity: 'warning',
        title: 'Missing .env.example',
        description: 'No .env.example file found to document required environment variables.',
        evidence: '.env.example not found in repository',
        suggestion: 'Create .env.example with all required environment variables documented.',
      },
      {
        id: 'license_present',
        category: 'license',
        severity: 'pass',
        title: 'License File Present',
        description: 'LICENSE file detected in repository.',
        evidence: 'LICENSE file found with MIT identifier',
        suggestion: 'License is properly configured.',
      },
      {
        id: 'readme_present',
        category: 'readme',
        severity: 'pass',
        title: 'README Present',
        description: 'README file detected in repository.',
        evidence: 'README.md found in repository root',
        suggestion: 'README is present and accessible.',
      },
    ],
    aiRecommendations: {
      summary: 'This repository has good structure but needs documentation improvements before submission. Critical issues include missing setup instructions and a committed .env file that should be removed.',
      prioritized: [
        {
          findingId: 'readme_missing_setup',
          priority: 1,
          title: 'Add Missing Setup Instructions',
          explanation: 'Without clear setup instructions, judges and reviewers cannot reproduce your project. This is a critical submission gap.',
          suggestedAction: 'Add a detailed "Getting Started" section with installation commands, prerequisites, and first-run instructions.',
        },
        {
          findingId: 'security_committed_env',
          priority: 2,
          title: 'Remove Committed .env File',
          explanation: 'Committed environment files may contain sensitive credentials and is a security risk.',
          suggestedAction: 'Remove .env from git history using BFG or git-filter-repo, add to .gitignore, and create .env.example instead.',
        },
        {
          findingId: 'readme_missing_env',
          priority: 3,
          title: 'Document Environment Variables',
          explanation: 'Users need to know which environment variables are required to run the project.',
          suggestedAction: 'Add an "Environment Variables" section to README documenting all required variables with examples.',
        },
        {
          findingId: 'links_broken_demo',
          priority: 4,
          title: 'Fix or Remove Demo Link',
          explanation: 'Broken demo links create a poor user experience and may hurt your submission score.',
          suggestedAction: 'Update the demo URL to a working deployment or remove the link if no demo is available.',
        },
      ],
      overallAdvice: 'Focus on documentation completeness and security hygiene. The codebase appears solid, but submission readiness is blocked by missing setup instructions and the committed .env file. Fix these critical issues first, then address the warnings to reach submission-ready status.',
    },
    checkDurationMs: 4500,
  };
}
